### ISSUE TITLE
Video links broken in faq/start/browser-extensions

### ISSUE THREAD

**Issue by aAlexanderLeben** [passbolt/passbolt_help#100]
Both video links in _faq/start/000-install-browser-extensions.md return 404

See https://help.passbolt.com/faq/start/browser-extensions

Sources:

  - https://github.com/passbolt/passbolt_help/blob/baeb961bfb0020c84ce028d644889b45e41bdbe8/_faq/start/000-install-browser-extensions.md?plain=1#L20
  - https://github.com/passbolt/passbolt_help/blob/baeb961bfb0020c84ce028d644889b45e41bdbe8/_faq/start/000-install-browser-extensions.md?plain=1#L43

**Comment by qntoni** [comment]
Hello @aAlexanderLeben,
Thank you for your feedback!

A ticket has been in created in order to fix this issue. Ref. PB-26157

Best regards

**Comment by qntoni** [comment]
Hello,

The issue regarding the video links returning 404 has been fixed. 

Thanks again for your help!

Best regards,
Antony
