### ISSUE TITLE
debian installer: wrong checksum

### ISSUE THREAD

**Issue by d-a-v** [passbolt/passbolt_help#102]
https://www.passbolt.com/ce/debian

**Comment by d-a-v** [comment]
Steps to reproduce:
```
$  wget "https://download.passbolt.com/ce/installer/passbolt-repo-setup.ce.sh"
$  wget "https://github.com/passbolt/passbolt-dep-scripts/releases/latest/download/passbolt-ce-SHA512SUM.txt"
$  sha512sum -c passbolt-ce-SHA512SUM.txt
passbolt-repo-setup.ce.sh: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
```

**Comment by Tecnobutrul** [comment]
@d-a-v thank you for the heads up! We had an issue during the scripts publishing, should be fixed now.

**Comment by d-a-v** [comment]
Thanks !

**Comment by kenshincheg** [comment]
Hello!
Help me please.
sha512sum -c passbolt-ce-SHA512SUM.txt && sudo bash ./passbolt-repo                                                                                                 -setup.ce.sh  || echo \"Bad checksum. Aborting\" && rm -f passbolt-repo-setup.ce.sh
passbolt-repo-setup.ce.sh: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
"Bad checksum. Aborting"
System - ubuntu 22
