### ISSUE TITLE
Documentation is wrong for cake command on https://help.passbolt.com/faq/hosting/why-email-not-sent

### ISSUE THREAD

**Issue by RandomUser0815** [passbolt/passbolt_help#106]
https://help.passbolt.com/faq/hosting/why-email-not-sent

Wrong:

sudo -H -u www-data bash -c "/usr/share/php/passbolt/bin/cake passbolt send_test_email [[email protected]]"

Right:

sudo -H -u www-data bash -c "/usr/share/php/passbolt/bin/cake passbolt send_test_email --recipient=[[email protected]]"

**Comment by qntoni** [comment]
Hello @RandomUser0815, thanks for your interest.

I took a look at the ![current documentation](https://github.com/passbolt/passbolt_help/assets/115071593/6a1d08f1-3967-4c0a-8986-48dbe0e24dd2) and it has been already fixed on April 5th 2022 (ref. PB-14526).

Best regards,
Antony
