### ISSUE TITLE
update environment variables to reflect the change in the default backend

### ISSUE THREAD

**Issue by modernNeo** [passbolt/passbolt_help#11]
Remy mentioned in [this post](https://community.passbolt.com/t/how-to-setup-with-mariadb/1125/6?u=jace) that MariaDB is now the default backend.

I recommend changing the environment variables that are used with the docker command outlined on [this page](https://github.com/passbolt/passbolt_help/blob/master/docs/hosting/install/ce/docker.html#L226) so that the environment variables arent confusing.

**Comment by modernNeo** [comment]
@stripthis why was this closed? the environment variable on [this page](https://help.passbolt.com/hosting/install/ce/docker.html) still use `MYSQL` in their naming, rather than `MARIADB`

**Comment by stripthis** [comment]
@modernNeo We have decided not to fix the issue as it will break backward compatibility with existing setups. This is something we could do in a next major version however.
