### ISSUE TITLE
You mention it has to be installed on a vanilla server but no mention of Certbot

### ISSUE THREAD

**Issue by alexbudin** [passbolt/passbolt_help#14]
You have to include instructions on installing certbot before starting the process.

https://certbot.eff.org/all-instructions

**Comment by AnatomicJC** [comment]
Our documentations pages have been updated. certbot setup is now handled with our [passbolt-repo-setup](https://github.com/passbolt/passbolt-dep-scripts/blob/main/passbolt-repo-setup.ce.sh) script.

https://help.passbolt.com/hosting/install
