### ISSUE TITLE
RSS is invalid

### ISSUE THREAD

**Issue by contman** [passbolt/passbolt_help#21]
This feed does not validate.

    line 4, column 6: link must be a full and valid URL: [help]

        <link></link>
              ^

In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.

    line 381, column 0: Missing atom:link with rel="self" [help]

        </channel>

Source: https://help.passbolt.com/releases/ce.rss

**Comment by stripthis** [comment]
Hello this is fixed,

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhelp.passbolt.com%2Freleases%2Fpro.rss

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhelp.passbolt.com%2Freleases%2Fce.rss

Thanks for the bug report.
