### ISSUE TITLE
Install instructions allow choosing between nginx and apache

### ISSUE THREAD

**Issue by thommierother** [passbolt/passbolt_help#28]

**Comment by thommierother** [comment]
During installation of passbolt behind a separate reverse proxy container (following instructions at https://help.passbolt.com/hosting/install/ce/from-source) I ran into a very time consuming issue:
install instructions are not reflecting the differences between the webservers with the highest market share (apache and nginx). 

So there is not an explicit requirement for mod_rewrite althoough it is needed for the location header functionality (/auth/login). The healthcheck does not check for the rewrite module and the requirements.php code only checks for missing php modules but not for modules in the webserver itself. Although this would be possible in php (e.g. for with apache_get_modules() ). For details see:

https://community.passbolt.com/t/installation-behind-nginx-rev-proxy-fails-2/2357/16

Requirement: add explicit information that both apache and nginx need active mod_rewrite modules

**Comment by stripthis** [comment]
Hello, 

Instructions in the help pages "Install passbolt API from source" do mention mod_rewrite.
https://help.passbolt.com/hosting/install/ce/from-source

![Screenshot 2020-01-26 at 14 35 20](https://user-images.githubusercontent.com/77410/73135987-21ad0980-4049-11ea-92ad-b1d11012fb6f.png)

We are a small team and try to limit the number of options (e.g. multiple distributions multiplied by webserver choice) in the documentation for installing passbolt, as it create support overhead. This may change as the team grow. 

We would welcome contribution in that direction.

**Comment by thommierother** [comment]
yep, I can support, no problem ,-) Are the install instructions managed through github? Then I could contribute directly ...

**Comment by dlen** [comment]
Yes @thommierother any contribution would be more than welcome! You can create a pull request in this very same repository. Make sure you take a look at the README first to know how jekyll works.

**Comment by thommierother** [comment]
see https://github.com/passbolt/passbolt_help/pull/29/commits/4700e6155608c2a0ca64bf4c6a703bee22f78a11
