### ISSUE TITLE
Review my backup restoration gist

### ISSUE THREAD

**Issue by fibonacid** [passbolt/passbolt_help#34]
Hello, i was looking at the documentation to find how to restore backups but other than the "Manual Installation" guide the resources were not very straightforward to me. I managed to make it work anyways and produced a gist to explain the process.

I was thinking about submitting this gist for review and maybe make a fork on this repository.

Here it is:
https://gist.github.com/lorenzorivosecchi/c048621a2db45e50b9cdffdfc6a2b892

Please let me know if you find any problems in my process

**Comment by AnatomicJC** [comment]
Hi,

Thanks for your contribution. Since this request, we added some documentation about how to [migrate to a new OS](https://help.passbolt.com/hosting/upgrade) using [backup](https://help.passbolt.com/hosting/backup).

Best regards,
