### ISSUE TITLE
Cannot install passbolt with composer v2 (still working with v1).

### ISSUE THREAD

**Issue by eyebank** [passbolt/passbolt_help#37]
Can this be resolved?

************************************************************************************************************
All settings correct for using Composer
Downloading...

Composer (version 2.0.0) successfully installed to: /usr/bin/composer.phar
Use it: php /usr/bin/composer.phar

===================================
Installing composer dependencies...
===================================
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - thadafinser/package-info is locked to version v1.0.0 and an update of this package was not requested.
    - thadafinser/package-info v1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - thadafinser/package-info v1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - thadafinser/user-agent-parser v2.0.0 requires thadafinser/package-info ^1.0 -> satisfiable by thadafinser/package-info[v1.0.0].
    - thadafinser/user-agent-parser is locked to version v2.0.0 and an update of this package was not requested.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
passbolt@pm:~$ thadafinser/package-info is locked to version v1.0.0 and an update of this package was not requested.
**********************************************************************************************

Composer upgraded:: (https://getcomposer.org/changelog/2.0.0)

2.0.0 - released 2020-10-24
View the release on GitHub

Changelog
Fixed proxy handling issues when combined with our new curl-based downloader
Fixed solver bug resulting in endless loops in some cases
Fixed solver output being extremely long due to learnt rules
Fixed solver bug with multi literals
Fixed a couple minor regressions
****************************************************************

Appreciate the help.

**Comment by cedricalfonsi** [comment]
Hello @eyebank ,

Thank you for the report. I can reproduce the issue with composer v2.

As a workaround, you can download and use composer v1, all the previous versions are still available on the composer website: https://getcomposer.org/download/.

Best regards

**Comment by eyebank** [comment]
@cedricalfonsi Several attempts to apply workaround failed. Can you provide guidance on how to proceed? 
Thanks.

**Comment by dlen** [comment]
Hi @eyebank ,

maybe this link could help https://github.com/composer/composer/issues/9329

**Comment by shishov** [comment]
@dlen I have same issue and it didn't work for me

**Comment by shishov** [comment]
I edited passbolt_ce_ubuntu_installer.sh and added
to line 797 option --version=1.10.16 after that script work fine
` php composer-setup.php --install-dir=/usr/bin --version=1.10.16`

**Comment by dlen** [comment]
Hi @shishov,

Can you try with the following release: https://github.com/passbolt/passbolt_install_scripts/releases/tag/v0.5.2

**Comment by eyebank** [comment]
@dlen I can confirm the release completed to installation without error.
Thanks.

**Comment by travispaul** [comment]
Should this issue be moved to [passbolt/passbolt_api](https://github.com/passbolt/passbolt_api) ? I ran into this issue and searched the open issues there first, then went to [community.passbolt](https://community.passbolt.com/t/installation-fails-due-to-composer-upgrade-to-version-2-00-on-10-24-2020/3222/4), and then finally to this repo.
