### ISSUE TITLE
MariahDB and MySQL in documentation

### ISSUE THREAD

**Issue by tbasten** [passbolt/passbolt_help#69]
https://help.passbolt.com/hosting/install/ce/ubuntu/ubuntu.html

In the section **Install passbolt official linux package** , the title and text refers to mariahdb however the pictures and the installation refer to MySQL.

**Comment by AnatomicJC** [comment]
I created a pull request for this, I will keep you informed as soon as it will be accepted and merged.

**Comment by AnatomicJC** [comment]
Hi,

Changes have been done here: https://github.com/passbolt/passbolt_help/commit/60a2052e10631f8ec2f5d9cbfbd504ced1869063

And merged in master here: https://github.com/passbolt/passbolt_help/commit/70353019a4e0c97ae5511228836544627f7a0248

Regards,
