### ISSUE TITLE
Broken link to guide on how to upgrade from CE to Pro version (Docker)

### ISSUE THREAD

**Issue by schopenhauer** [passbolt/passbolt_help#77]
https://help.passbolt.com/hosting/upgrade/pro/upgrade-pro-from-ce

linking to:

https://help.passbolt.com/hosting/upgrade/pro/upgrade-pro-from-v2-docker - not found

**Comment by claytontstevenson** [comment]
Hey @schopenhauer thanks for letting us know, I've created an internal ticket to fix this under CS-62

**Comment by claytontstevenson** [comment]
Added a warning on the page as the current instructions are found elsewhere.
