### ISSUE TITLE
database issues with docker container

### ISSUE THREAD

**Issue by martijnhiemstra** [passbolt/passbolt_help#9]
I am using the passbolt docker image and when I start up my database and passbolt I get the following error:

Base table or view not found

This means that passbolt doesn't automatically create the tables and if your using docker then you haven't got the sql file to initialize the tables. This needs to be fixed otherwise the docker container is useless.

**Comment by dlen** [comment]
Hi @martijnhiemstra sorry to hear that.
Could you first open this issue on https://github.com/passbolt/passbolt_docker repo to continue there the discussion? 
Also could you provide any information to debug the issue as required in the issue template such as logs, screenshots, etc?
Lastly your issue might be related with https://github.com/passbolt/passbolt_docker/issues/92
