### ISSUE TITLE
Outdated Statement regarding Security audits

### ISSUE THREAD

**Issue by karpfediem** [passbolt/passbolt_help#97]
I assume the statement

https://github.com/passbolt/passbolt_help/blob/0b130eb7abc10a497f30a80b6f20197587aafa8a/_faq/security/001-has-the-code-been-reviewed.md?plain=1#L10
references exactly the 7 reports listed in total. 
I found this confusing since there are only 5 reports within the last 24 months listed. Should be a simple fix by rephrasing.

**Comment by claytontstevenson** [comment]
Thanks for the report @karpfediem we've since updated the language on this page to be more accurate
