### ISSUE TITLE
second auth factors

### ISSUE THREAD

**Issue by OperativeThunny** [passbolt/passbolt_help#98]
I would like the ability to register multiple yubikeys instead of only one for 2fa. 

I would also like to be able to authenticate using WebAuthN as a second factor so I can add multiple passkeys (yubikey, fido2 cards, phones, etc...)

**Comment by garrettboone** [comment]
Hi @OperativeThunny This can be posted in the [Feature Requests ](https://community.passbolt.com/c/backlog/6)  section of the forum.

**Comment by OperativeThunny** [comment]
Oops, my bad, I will go there. Thanks for the link and direction to the correct place to put this request!
